/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class atari800_NativeInterface */

#ifndef _Included_atari800_NativeInterface
#define _Included_atari800_NativeInterface
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     atari800_NativeInterface
 * Method:    init
 * Signature: (Latari800/NativeClient;)V
 */
JNIEXPORT void JNICALL Java_atari800_NativeInterface_init
  (JNIEnv *, jclass, jobject);

/*
 * Class:     atari800_NativeInterface
 * Method:    main
 * Signature: ([Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_atari800_NativeInterface_main
  (JNIEnv *, jclass, jobjectArray);

/*
 * Class:     atari800_NativeInterface
 * Method:    getMemory
 * Signature: ()[B
 */
JNIEXPORT jbyteArray JNICALL Java_atari800_NativeInterface_getMemory
  (JNIEnv *, jclass);

/*
 * Class:     atari800_NativeInterface
 * Method:    getStatus
 * Signature: ()[I
 */
JNIEXPORT jintArray JNICALL Java_atari800_NativeInterface_getStatus
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
