/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class atari800_NativeInterface */

#ifndef _Included_atari800_NativeInterface
#define _Included_atari800_NativeInterface
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     atari800_NativeInterface
 * Method:    setNativeClient
 * Signature: (Latari800/NativeClient;)V
 */
JNIEXPORT void JNICALL Java_atari800_NativeInterface_init
  (JNIEnv *, jclass, jobject);

#ifdef __cplusplus
}
#endif
#endif
