/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class atari800_Atari800 */

#ifndef _Included_atari800_Atari800
#define _Included_atari800_Atari800
#ifdef __cplusplus
extern "C" {
#endif
#undef atari800_Atari800_FOCUS_TRAVERSABLE_UNKNOWN
#define atari800_Atari800_FOCUS_TRAVERSABLE_UNKNOWN 0L
#undef atari800_Atari800_FOCUS_TRAVERSABLE_DEFAULT
#define atari800_Atari800_FOCUS_TRAVERSABLE_DEFAULT 1L
#undef atari800_Atari800_FOCUS_TRAVERSABLE_SET
#define atari800_Atari800_FOCUS_TRAVERSABLE_SET 2L
#undef atari800_Atari800_TOP_ALIGNMENT
#define atari800_Atari800_TOP_ALIGNMENT 0.0f
#undef atari800_Atari800_CENTER_ALIGNMENT
#define atari800_Atari800_CENTER_ALIGNMENT 0.5f
#undef atari800_Atari800_BOTTOM_ALIGNMENT
#define atari800_Atari800_BOTTOM_ALIGNMENT 1.0f
#undef atari800_Atari800_LEFT_ALIGNMENT
#define atari800_Atari800_LEFT_ALIGNMENT 0.0f
#undef atari800_Atari800_RIGHT_ALIGNMENT
#define atari800_Atari800_RIGHT_ALIGNMENT 1.0f
#undef atari800_Atari800_serialVersionUID
#define atari800_Atari800_serialVersionUID -7644114512714619750LL
#undef atari800_Atari800_serialVersionUID
#define atari800_Atari800_serialVersionUID 4613797578919906343LL
#undef atari800_Atari800_INCLUDE_SELF
#define atari800_Atari800_INCLUDE_SELF 1L
#undef atari800_Atari800_SEARCH_HEAVYWEIGHTS
#define atari800_Atari800_SEARCH_HEAVYWEIGHTS 1L
#undef atari800_Atari800_serialVersionUID
#define atari800_Atari800_serialVersionUID -2728009084054400034LL
#undef atari800_Atari800_serialVersionUID
#define atari800_Atari800_serialVersionUID -5836846270535785031LL
#ifdef __cplusplus
}
#endif
#endif
